install nektos/tap/act
install asdf
install autojump
install curl
install fish
install gcsfuse
install gh
install git
install git-flow
install gnupg
install graphviz
install hdf5
install hyperkit
install minikube
install poetry
install postgresql
install ripgrep
install starship
install thefuck
